#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# beryllium (Poco F1): the WCN3990 has no valid stored WiFi MAC, so ath10k picks
# a RANDOM MAC every boot (-> new DHCP lease / IP each time). ath10k ignores a
# DT MAC, so fix it in userspace: derive a stable, locally-administered MAC from
# the persisted machine-id and set it as NetworkManager's cloned MAC for WiFi.
MID=$(cat /etc/machine-id 2>/dev/null)
[ -n "${MID}" ] || exit 0
MAC=$(printf '02:%s' "$(echo "${MID}" | sed -E 's/^(..)(..)(..)(..)(..).*/\1:\2:\3:\4:\5/')")
mkdir -p /run/NetworkManager/conf.d
cat > /run/NetworkManager/conf.d/00-beryllium-stable-wifi-mac.conf <<INNER
[connection]
wifi.cloned-mac-address=${MAC}
INNER
exit 0
